config/routes.rb
Rails.application.routes.draw do
  root to: "buddies#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :buddies
  resource :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  belongs_to :user, optional: true
  before_save { self.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE_REGEX = /\A[1(]?[-]?\d{3}[-).]?\s?\d{3}[-.]?\d{4}\z/

  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :phone, format: { with: VALID_PHONE_REGEX }
  validates :age, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :buddies, dependent: :destroy

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_buddy, only: %i[ show edit update destroy ]

  def index
    @buddies = Buddy.all.order(created_at: :DESC)
  end

  def new
    @buddy = Buddy.new
  end

  def create
    @buddy = current_user.buddies.build(buddy_params)

    if @buddy.save
      redirect_to @buddy, notice: "Buddy was successfully created"
    else
      flash.now[:alert] = "Buddy was NOT created!"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @buddy.update(buddy_params)
      redirect_to @buddy, notice: "Buddy was successfully updated"
    else
      flash.now[:alert] = "Buddy was NOT updated"
      render :edit
    end
  end

  def destroy
    @buddy.destroy
    redirect_to users_path, alert: "Buddy was successfully deleted"
  end

  private

  def set_buddy
    @buddy = Buddy.find(params[:id])
  end

  def buddy_params
    params.require(:buddy).permit(:first_name, :last_name, :email, :phone, :age)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_guest_user, only: :create

  def ensure_guest_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "The guest user's password cannot be reset"
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_guest_user, only: %i[update destroy]

  def ensure_guest_user
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "The guset user cannot be updated or/and deleted"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path, notice: "Logged in as a guest user"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @buddies = current_user.buddies.order(created_at: :DESC)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buddies_helper.rb
module BuddiesHelper
  def full_name(buddy)
    buddy.first_name + ' ' + buddy.last_name
  end

  def nickname_or_email(buddy)
    buddy.user.nickname.present? ? "#{buddy.user.nickname}" : "#{buddy.user.email}"
  end
end

app/views/buddies/_form.html.erb
<%= render "layouts/error" %>

<%= form_with model: @buddy, local: true do |form| %>
  <div class="field form-group mb-3">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control", placeholder: "First name", required: true, maxlength: 30 %>
  </div>

  <div class="field form-group mb-3">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last name", required: true, maxlength: 30 %>
  </div>

  <div class="field form-group mb-3">
    <% form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "Email", required: true, maxlength: 255 %>
  </div>

  <div class="field form-group mb-3">
    <% form.label :phone %>
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone i.e. 000-111-2222" %>
  </div>

  <div class="field form-group mb-3">
    <% form.label :age %>
    <%= form.text_field :age, class: "form-control", placeholder: "age" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit class: "btn btn-primary form-control" %>
  </div>
<% end %>

app/views/buddies/_home.html.erb
<div class="card text-center">
  <div class="card-header">
    <h1>Welcome to Buddy App!</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title mb-3">Let's make buddies!</h5>
    <% if user_signed_in? %>
      <%= link_to "Add Buddies", new_buddy_path, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-secondary" %>
      <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary" %>
      <%= link_to "Login As Guest User", users_guest_sign_in_path, method: :post, class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

app/views/buddies/edit.html.erb
<h2 class="text-center mb-3">Edit Buddy</h2>

<%= render "form" %>

<%= link_to "Back", users_path, class: "btn btn-secondary form-control" %>

app/views/buddies/index.html.erb
<% if user_signed_in? %>
  <h2 class="text-center mb-3">Buddy List</h2>
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Age</th>
          <th>User</th>
        </tr>
      </thead>

      <tbody>
        <% @buddies.each do |buddy| %>
          <tr>
            <td><%= full_name(buddy) %></td>
            <td><%= buddy.email %></td>
            <td><%= buddy.phone %></td>
            <td><%= buddy.age %></td>
            <td><%= nickname_or_email(buddy) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to "New Buddy", new_buddy_path, class: "btn btn-primary form-control" %>
<% else %>
  <%= render "home" %>
<% end %>

app/views/buddies/new.html.erb
<h2 class="text-center mb-3">Add New Buddy</h2>

<%= render "form" %>

<%= link_to "Back to Buddy List", buddies_path, class: "btn btn-secondary form-control" %>

app/views/buddies/show.html.erb
<div class="card mb-3">
  <div class="card-header text-center">
    <h2 class="card-title"><%= full_name(@buddy) %></h2>
  </div>
  <ul class="list-group list-group-flush text-center">
    <li class="list-group-item"><%= @buddy.email %></li>
    <li class="list-group-item"><%= @buddy.phone %></li>
    <li class="list-group-item"><%= @buddy.age %></li>
  </ul>
  <div class="card-body text-center">
    <%= link_to 'Edit', edit_buddy_path(@buddy), class: "btn btn-outline-secondary" %>
    <%= link_to 'Delete', @buddy, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
  </div>
</div>
<%= link_to 'Back to My Buddy List', users_path, class: "btn btn-secondary form-control mb-3" %>

app/views/layouts/_error.html.erb
<% if @buddy.errors.any? %>
  <% @buddy.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">x</a>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Buddy App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item p-2 text-white">
            <%= current_user.nickname.present? ? "【USER: #{current_user.nickname}】" : "【USER: #{current_user.email}】" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Buddies", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Buddies", new_buddy_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login As Guest User", users_guest_sign_in_path, method: :post, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buddies List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="container mt-5">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<h2 class="text-center mb-3">My Buddy List</h2>
<% @buddies.each do |buddy| %>
  <%= link_to(buddy_path(buddy), class: "text-decoration-none text-dark") do %>
    <div class="card bg-light text-dark mb-3">
      <div class="card-body buddy-card">
        <h3 class="card-title">
          <%= buddy.first_name %>
          <%= buddy.last_name %>
        </h3>
        <p class="card-text">
          <i class="fa-solid fa-envelope"></i><span class="ms-1"><%= buddy.email %></span>
          <i class="fa-solid fa-square-phone"></i><span class="ms-1"><%= buddy.phone %></span>
          <i class="fa-solid fa-image-portrait"></i><span class="ms-1"><%= buddy.age %></span>
        </p>
      </div>
    </div>
  <% end %>
<% end %>
<%= link_to "New Buddy", new_buddy_path, class: "btn btn-primary form-control mb-3" %>
<%= link_to 'Back to Buddy List', root_path, class: "btn btn-secondary form-control mb-3" %>